# Roboflow dataset
dataset_url: "https://universe.roboflow.com/ds/AGwYvP3noP?key=${STRAWBERRY_DISEASE_KEY}"
data_dir : "data"

# Local path
base_dir: "/home/aiot-garage/RabindraManandhar/Strawberry_Health_AI"

# Class names
class_names: ['Angular Leafspot', 'Anthracnose Fruit Rot', 'Blossom Blight', 'Gray Mold', 'Leaf Spot', 'Powdery Mildew Fruit', 'Powdery Mildew Leaf']

# Training Hyperparameters
epochs: 100               # Number of training epochs
batch_size: 32            # Batch size
img_size: 640             # Input image size

# Raspberry Pi server IP and port
server_url: "http://192.168.50.148:8000"
upload_dir: "uploaded_images"
download_dir: "downloaded_images"

# Camera Image Frames
transormed_frames_dir: "transformed_frames"

# Transformed Images
transformed_images_dir: "transformed_images"


