dataset_url: "https://universe.roboflow.com/ds/AGwYvP3noP?key=${STRAWBERRY_DISEASE_KEY}"
output_dir : "data"

base_dir: "/home/aiot-garage/Strawberry_Health_AI"

new_image_path: "images"

class_names: ['Angular Leafspot', 'Anthracnose Fruit Rot', 'Blossom Blight', 'Gray Mold', 'Leaf Spot', 'Powdery Mildew Fruit', 'Powdery Mildew Leaf']

# Training Hyperparameters
epochs: 100                # Number of training epochs
batch_size: 16            # Batch size
img_size: 640             # Input image size



